CREATE PROCEDURE [dbo].[ALTERA_SENHA]
@PROPRIETARIO_AP INT,
@PROPRIETARIO_BLOCO INT,
@NOVA_SENHA VARCHAR(50)

AS
      
      BEGIN
      
      UPDATE Proprietario SET PASSWORD = @NOVA_SENHA 
        WHERE  PROPRIETARIO_AP = @PROPRIETARIO_AP
              AND PROPRIETARIO_BLOCO = @PROPRIETARIO_BLOCO
 
     
 
      END


