---
CREATE PROCEDURE [dbo].[AUTENTICA_MORADOR]
@PROPRIETARIO_AP INT,
@PROPRIETARIO_BLOCO INT,
@SENHA VARCHAR(50),
@RETORNO INT OUTPUT
AS
	
	BEGIN
	
	SELECT @RETORNO = (SELECT COUNT(PROPRIETARIO_AP) FROM Proprietario 
	WHERE  PROPRIETARIO_AP = @PROPRIETARIO_AP
	AND PROPRIETARIO_BLOCO = @PROPRIETARIO_BLOCO
	AND PASSWORD  =@SENHA)

	END


