CREATE PROCEDURE [dbo].[LISTA_CHURRAS_MORADOR]
@BLOCO INT,
@AP INT,
@ANO VARCHAR(12),
@MES VARCHAR(12)
AS
BEGIN
	
	SELECT PROPRIETARIO_BLOCO,PROPRIETARIO_AP, SALAO_CHURRASCO FROM AGENDA 
	WHERE PROPRIETARIO_BLOCO = @BLOCO
	AND PROPRIETARIO_AP  = @AP
	AND SALAO_CHURRASCO = 'S'
	AND YEAR(DATA_AGENDAMENTO) = @ANO
	AND MONTH(DATA_AGENDAMENTO) = @MES
END


