CREATE PROCEDURE [dbo].[VALIDA_MORADOR_CADASTRO]
@PROPRIETARIO_AP INT,
@PROPRIETARIO_BLOCO INT
AS
	BEGIN
	
	SELECT COUNT(PROPRIETARIO_AP) FROM Proprietario
	WHERE  PROPRIETARIO_AP = @PROPRIETARIO_AP
	AND PROPRIETARIO_BLOCO = @PROPRIETARIO_BLOCO
	
	END


