CREATE TABLE [dbo].[AGENDA](
	[DATA_AGENDAMENTO] [datetime] NOT NULL,
	[PROPRIETARIO_BLOCO] [int] NOT NULL,
	[PROPRIETARIO_AP] [int] NOT NULL,
	[SALAO_FESTA] [char](10) NOT NULL,
	[SALAO_CHURRASCO] [char](10) NOT NULL
) ON [PRIMARY]


