USE [Azulli]
GO

/****** Object:  Table [dbo].[HISTORICO_CANCELAMENTO]    Script Date: 02/20/2013 17:02:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HISTORICO_CANCELAMENTO](
	[ID_HISTORICO] [int] IDENTITY(1,1) NOT NULL,
	[BLOCO] [varchar](50) NOT NULL,
	[AP] [varchar](50) NOT NULL,
	[DATA_AGENDAMETO] [datetime] NOT NULL,
	[AREA] [varchar](50) NOT NULL,
	[DATA_CANCELAMENTO] [datetime] NULL,
 CONSTRAINT [PK_HISTORICO_CANCELAMENTO] PRIMARY KEY CLUSTERED 
(
	[ID_HISTORICO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


