CREATE TABLE [dbo].[LANCAMENTO_OCORRENCIA](
	[OCORRENCIA] [varchar](50) NOT NULL,
	[DATA_OCORRENCIA] [datetime] NULL,
	[STATUS] [char](1) NULL,
	[DESCRICAO] [varchar](250) NULL,
	[BLOCO] [int] NOT NULL,
	[AP] [int] NOT NULL,
	[CODIGO_OCORRENCIA] [int] NOT NULL,
	[DATA_FINALIZACAO] [datetime] NULL,
	[DATA_CANCELAMENTO] [datetime] NULL,
 CONSTRAINT [PK_OCORRENCIA] PRIMARY KEY CLUSTERED 
(
	[OCORRENCIA] ASC,
	[BLOCO] ASC,
	[AP] ASC,
	[CODIGO_OCORRENCIA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


