CREATE TABLE [dbo].[MENSAGEM_MORADOR](
	[ID_MSG] [int] IDENTITY(1,1) NOT NULL,
	[BLOCO] [int] NOT NULL,
	[APARTAMENTO] [int] NOT NULL,
	[MENSAGEM] [varchar](3000) NOT NULL,
	[STATUS] [nchar](10) NOT NULL,
	[ATIVO] [char](2) NOT NULL,
	[DATAINICIOVIGENCIA] [datetime] NULL,
	[DATAFIMVIGENCIA] [datetime] NULL,
 CONSTRAINT [PK_MENSAGEM_MORADOR] PRIMARY KEY CLUSTERED 
(
	[ID_MSG] ASC,
	[BLOCO] ASC,
	[APARTAMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


