CREATE TABLE [dbo].[OCORRENCIA](
	[CODIGO] [int] NOT NULL,
	[DESCRICAO] [varchar](50) NOT NULL,
	[STATUS] [char](10) NOT NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
 CONSTRAINT [PK_OCORRENCIA_1] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


